### ISSUE TITLE
Please update to 1.0.18

### ISSUE THREAD

**Issue by tokuhirom** [timbunce/Memcached-libmemcached#11]
This release contains fix for following this issue.
https://bugs.launchpad.net/libmemcached/+bug/1216521

**Comment by sburke-at-rent-com** [comment]
Note that a trial release that corrects these build issues is available at http://search.cpan.org/~seanburke/Memcached-libmemcached/

**Comment by timbunce** [comment]
Hi. Any news on this?

**Comment by sburke-at-connectivity** [comment]
I have not gotten any feedback, good or bad, regarding the 1.001800 trial releases.
How would you like to proceed?

**Comment by timbunce** [comment]
Ship it! :)

That's a good way to get feedback ;)
 
Thanks!

**Comment by wolfsage** [comment]
Also cpantesters looks good http://matrix.cpantesters.org/?dist=Memcached-libmemcached+1.001801-TRIAL2

**Comment by sburke-at-connectivity** [comment]
TRIAL2, as i recall, includes the changes in pull request 18. OK to merge that PR?

**Comment by timbunce** [comment]
Yeap, please do. We can also push another trial release anyway just to be sure.

**Comment by ghost** [comment]
Pull request 18 is merged, and release 1.001801 is tagged and cut.
I'll upload this to PAUSE as Memcached-libmemcached-1.001801.tar.gz

**Comment by timbunce** [comment]
Great. Thanks @sburke-at-connectivity. I hadn't got around to replying to your email but you seem comfortable enough with the process. Let me know if you need any help or clarification etc.

**Comment by ghost** [comment]
I've uploaded 1.001801 as -TRIAL3 to CPAN, and done test builds on:
- Ubuntu 14.04 perl 5.18.2
- Centos 6.5 perl 5.16.2
- MacOSX 10.9.5 perl 5.16.2

I will upload it without the TRIAL3 suffix next week, if no problems arise.

**Comment by wolfsage** [comment]
Awesome, thanks a lot for taking this on.

**Comment by ghost** [comment]
Version 1.001801 is now on CPAN at 
http://search.cpan.org/src/SEANBURKE/Memcached-libmemcached-1.001801/

**Comment by timbunce** [comment]
Yeah. Thanks @sburke-at-connectivity!
