### ISSUE TITLE
Mac OS X 10.10 error: 'tr1/cinttypes' file not found

### ISSUE THREAD

**Issue by 1371030** [timbunce/Memcached-libmemcached#14]
OS X 10.10 Yosemite Xcode 6.1
tr1/cinttypes in /usr/include
Memcached-libmemcached-1.001702 perl model download for search.cpan.org

sudo perl Makefile.pl
...
./libmemcached-1.0/memcached.h:46:12: fatal error: 'tr1/cinttypes' file not found

#  include <tr1/cinttypes>
           ^

**Comment by ghost** [comment]
This problem should be fixed in the current 1.001801 release.
